#!/bin/sh

# installation of .emacs.d and cask

cd ~
brew install emacs
git clone https://github.com/jeena/emacs.d.git .emacs.d
curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
echo "export PATH=\"$HOME/.cask/bin:\$PATH\"" >> .zshrc
source .zshrc
cask upgrade-cask
cd .emacs.d/
cask install
